# Source: cluster-api-aws/templates/kubeadm-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: cats4tw1t-control-plane
  namespace: cats4tw1t
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: tks-seoul
      rootVolume:
        size: 20
        type: gp2
